<a href="https://colab.research.google.com/github/cesarrivera52/Examen1/blob/main/lastmile_delivery_operations_mit_lift_lab_serving_customer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#César Alejandro Rivera Guzmán  A01567012
#Examen progra
#Last Mile Delivery Operation MIT Lift Lab Serving

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import io

from google.colab import files
files.upload()

In [2]:
datam=pd.read_csv('lastmile_delivery_operations_mit_lift_lab_serving_customer.csv')
datam

,_child_record_id,_record_id,_parent_id,_title,_version,_created_at,_updated_at,_created_by,_updated_by,_index,...,name_of_the_store,entering_the_store,number_of_customers_in_store,number_of_suppliers_in_store,picture_cargo_being_delivered,picture_cargo_being_delivered_captions,picture_cargo_being_delivered_urls,number_of_cases_boxes_delivered,trolley_in_use,leaving_the_store
0,12645bc3-33b6-4cc0-9c8e-9d8e6f35aa01,04e64464-3fbd-4ce1-99d8-5364e1567e8c,04e64464-3fbd-4ce1-99d8-5364e1567e8c,La fete,1,2022-11-12 18:00:54 UTC,2022-11-12 18:02:03 UTC,Juan Carlos Bejarano Moreno,Juan Carlos Bejarano Moreno,0,...,La fete,23:50,1,1,https://web.fulcrumapp.com/photos/view?photos=...,",",https://web.fulcrumapp.com/api/v2/file?context...,15,no,12:12
1,be0fc402-769c-41f8-90f1-1b0c9f151e7a,cda7b134-7827-4830-9337-53f46be4f8b4,cda7b134-7827-4830-9337-53f46be4f8b4,Casa Flores,1,2022-11-12 16:54:27 UTC,2022-11-12 16:55:48 UTC,Juan Carlos Bejarano Moreno,Juan Carlos Bejarano Moreno,0,...,Casa Flores,10:35,0,2,https://web.fulcrumapp.com/photos/view?photos=...,",",https://web.fulcrumapp.com/api/v2/file?context...,35,no,11:00
2,634bbd94-8159-4733-973a-36ab89fb95d4,cbaab095-ad31-4145-804b-ddc218681802,cbaab095-ad31-4145-804b-ddc218681802,Super deux,1,2022-11-12 16:43:26 UTC,2022-11-12 16:45:00 UTC,Juan Carlos Bejarano Moreno,Juan Carlos Bejarano Moreno,0,...,Super deux,10:35,0,1,https://web.fulcrumapp.com/photos/view?photos=...,NaN,https://web.fulcrumapp.com/api/v2/file?context...,12,no,10:50
3,cf8e05ea-0af9-4a66-9d8b-27c0cf572236,68b5ecad-36b0-4172-b2b3-43aebd0485ec,68b5ecad-36b0-4172-b2b3-43aebd0485ec,Dansk,1,2022-11-12 16:37:55 UTC,2022-11-12 16:38:54 UTC,Juan Carlos Bejarano Moreno,Juan Carlos Bejarano Moreno,0,...,Dansk,10:22,0,1,https://web.fulcrumapp.com/photos/view?photos=...,NaN,https://web.fulcrumapp.com/api/v2/file?context...,3,no,10:43
4,a1ff05ef-fe15-472e-ad6d-537c951afce4,3b19bb47-17f0-4d33-aa27-cf6890bacfe5,3b19bb47-17f0-4d33-aa27-cf6890bacfe5,Ink Factory,1,2022-11-12 16:19:57 UTC,2022-11-12 16:21:14 UTC,Juan Carlos Bejarano Moreno,Juan Carlos Bejarano Moreno,0,...,Ink Factory,10:13,0,1,https://web.fulcrumapp.com/photos/view?photos=...,NaN,https://web.fulcrumapp.com/api/v2/file?context...,1,yes,10:33
5,9e96f584-f5b2-4e7d-a754-a34fc89d5139,2b8a179a-521c-4ee3-a5ef-241fd1972b01,2b8a179a-521c-4ee3-a5ef-241fd1972b01,Breaking Bread Coffee,1,2022-11-12 15:59:13 UTC,2022-11-12 16:00:07 UTC,Juan Carlos Bejarano Moreno,Juan Carlos Bejarano Moreno,0,...,Breaking Bread Coffee,09:48,7,1,https://web.fulcrumapp.com/photos/view?photos=...,NaN,https://web.fulcrumapp.com/api/v2/file?context...,3,no,10:06
6,531eb119-cab7-4ba9-8a25-489e91ec2a5a,3aa26fc8-4373-4387-ac50-4f7b0d417107,3aa26fc8-4373-4387-ac50-4f7b0d417107,Abarrotes vinos y licores La ranita,1,2022-11-10 18:31:16 UTC,2022-11-11 01:23:59 UTC,Sandra Carreón,Sandra Carreón,0,...,Abarrotes vinos y licores La ranita,12:29,1,1,NaN,NaN,NaN,3,no,12:33
7,17995e32-9ed3-4a27-8da3-b4e1d942ad36,5288fd44-2899-4765-9195-3f866d2e6d45,5288fd44-2899-4765-9195-3f866d2e6d45,Abarrotes vinos y licores La ranita,1,2022-11-11 04:30:19 UTC,2022-11-11 05:27:33 UTC,Sandra Carreón,Sandra Carreón,0,...,Abarrotes vinos y licores La ranita,12:56,2,1,NaN,NaN,NaN,3,no,13:01
8,009bf340-321a-4739-84b4-d80029770d10,d1662ccd-4787-4c38-969a-a9e8a01ad1c2,d1662ccd-4787-4c38-969a-a9e8a01ad1c2,Mony,1,2022-11-11 22:44:44 UTC,2022-11-11 22:46:40 UTC,Sandra Carreón,Sandra Carreón,0,...,Mony,16:28,2,1,NaN,NaN,NaN,2,no,16:28
9,c78336c3-d0ab-4e08-bc2e-f15af41f76fb,6f431744-a51b-4b36-b33f-13fb860ef131,6f431744-a51b-4b36-b33f-13fb860ef131,Tomales y molino Anita,1,2022-11-04 21:57:43 UTC,2022-11-04 22:11:37 UTC,José Varela,José Varela,0,...,Tomales y molino Anita,16:02,3,2,https://web.fulcrumapp.com/photos/view?photos=...,NaN,https://web.fulcrumapp.com/api/v2/file?context...,11,yes,16:19
10,a616737c-bcb2-4ad0-a82a-4ca917fab0fc,56562b58-bfeb-4165-8e3b-7bc0a5a224cf,56562b58-bfeb-4165-8e3b-7bc0a5a224cf,La michoacana,1,2022-11-04 21:49:56 UTC,2022-11-04 21:52:44 UTC,José Varela,José Varela,0,...,La michoacana,15:40,2,2,https://web.fulcrumapp.com/photos/view?photos=...,NaN,https://web.fulcrumapp.com/api/v2/file?context...,12,yes,15:55
11,8e4d79db-4fa9-4c83-ba72-88b109a2a71b,af1d6ac9-3e31-42de-a4d2-873c080b8766,af1d6ac9-3e31-42de-a4d2-873c080b8766,Los globos,1,2022-11-10 17:33:57 UTC,2022-11-10 17:36:08 UTC,Sandra Carreón,Sandra Carreón,0,...,Los globos,11:21,9,1,NaN,NaN,NaN,5,yes,11:30
12,89943c66-9129-458f-a295-6ecc61b4dfa2,9eac0dba-fb4b-4947-ba68-c406dadb6887,9eac0dba-fb4b-4947-ba68-c406dadb6887,Muebles Bustos,1,2022-11-10 16:26:45 UTC,2022-11-10 16:32:13 UTC,Sandra Carreón,Sandra Carreón,0,...,Muebles Bustos,10:15,0,1,NaN,NaN,NaN,24,no,10:32
13,044b47df-e630-4ca7-ac15-2ba322760aae,e3de2e0f-79f4-4698-a6e4-064aa921a5fb,e3de2e0f-79f4-4698-a6e4-064aa921a5fb,Gaspachos Morelianos,1,2022-11-10 17:35:22 UTC,2022-11-10 17:36:41 UTC,Mariana Sáenz Gómez Ortigoza,Mariana Sáenz Gómez Ortigoza,0,...,Gaspachos Morelianos,11:35,1,3,https://web.fulcrumapp.com/photos/view?photos=...,NaN,https://web.fulcrumapp.com/api/v2/file?context...,8,no,11:55
14,98e21e5a-b7cc-4314-813e-b4cd016fbe67,75037107-c676-446a-ba1d-ab04881a6f67,75037107-c676-446a-ba1d-ab04881a6f67,Factory Blinds,1,2022-11-10 17:35:17 UTC,2022-11-10 17:36:04 UTC,José López,José López,0,...,Factory Blinds,11:35,2,1,https://web.fulcrumapp.com/photos/view?photos=...,NaN,https://web.fulcrumapp.com/api/v2/file?context...,2,no,11:40
15,eb6170a1-74f1-4dca-ba9b-53614e8ce1e9,3b3b959a-bc54-4825-8d79-f8e957a0355b,3b3b959a-bc54-4825-8d79-f8e957a0355b,Cabo San Lucas,1,2022-11-10 17:25:17 UTC,2022-11-10 17:26:07 UTC,Mariana Sáenz Gómez Ortigoza,Mariana Sáenz Gómez Ortigoza,0,...,Cabo San Lucas,11:31,2,5,NaN,NaN,NaN,10,yes,11:38
16,83fd3b7d-52b4-45d0-8f25-df98b6229aed,1464422d-78c5-4cfa-afa6-5bf569e882d2,1464422d-78c5-4cfa-afa6-5bf569e882d2,Postrecitos lindos,1,2022-11-10 17:21:02 UTC,2022-11-10 17:21:59 UTC,Mariana Sáenz Gómez Ortigoza,Mariana Sáenz Gómez Ortigoza,0,...,Postrecitos lindos,11:30,0,2,NaN,NaN,NaN,6,yes,11:38
17,e45b69e0-5250-403b-a1f4-54daf1427ff8,98008626-eea4-4f9a-ab80-de6e7c716207,98008626-eea4-4f9a-ab80-de6e7c716207,Stop by ramen,1,2022-11-10 17:20:56 UTC,2022-11-10 17:21:37 UTC,José López,José López,0,...,Stop by ramen,11:21,0,1,https://web.fulcrumapp.com/photos/view?photos=...,NaN,https://web.fulcrumapp.com/api/v2/file?context...,2,no,11:30
18,7c0e3d41-b490-4940-8286-15fa3d8a5726,897dd608-be28-4337-b503-5dc70df1e2de,897dd608-be28-4337-b503-5dc70df1e2de,Súper boom,1,2022-11-10 17:11:09 UTC,2022-11-10 17:11:51 UTC,José López,José López,0,...,Súper boom,11:11,3,1,https://web.fulcrumapp.com/photos/view?photos=...,NaN,https://web.fulcrumapp.com/api/v2/file?context...,4,no,11:14
19,1788e007-9b6b-4cc4-aaf7-35d1b8143f32,f9dd984b-722a-4c26-aaef-d8ad2dff57b6,f9dd984b-722a-4c26-aaef-d8ad2dff57b6,Trípoli,1,2022-11-10 17:05:04 UTC,2022-11-10 17:06:25 UTC,José López,José López,0,...,Trípoli,10:43,2,1,https://web.fulcrumapp.com/photos/view?photos=...,NaN,https://web.fulcrumapp.com/api/v2/file?context...,2,no,11:56
20,c98cae40-7553-4755-a0f8-a51fbe275d12,94b03890-ef1b-4e87-bf0d-42bb64babb73,94b03890-ef1b-4e87-bf0d-42bb64babb73,La Medina,1,2022-11-10 17:01:02 UTC,2022-11-10 17:02:19 UTC,Mariana Sáenz Gómez Ortigoza,Mariana Sáenz Gómez Ortigoza,0,...,La Medina,11:08,4,3,https://web.fulcrumapp.com/photos/view?photos=...,NaN,https://web.fulcrumapp.com/api/v2/file?context...,6,no,11:25
21,348702bf-ec37-436e-ba06-fe8e54abab13,0494e54e-1037-4788-9e37-b6bab949011b,0494e54e-1037-4788-9e37-b6bab949011b,Súper boom,1,2022-11-10 17:00:44 UTC,2022-11-10 17:01:25 UTC,José López,José López,0,...,Súper boom,11:00,4,2,https://web.fulcrumapp.com/photos/view?photos=...,NaN,https://web.fulcrumapp.com/api/v2/file?context...,5,yes,11:20
22,383c55fc-f202-4a79-9425-eb7122d5e5e3,49b79862-d297-4391-bc6e-3e6d8b32d54a,49b79862-d297-4391-bc6e-3e6d8b32d54a,La Voila,1,2022-11-10 16:47:11 UTC,2022-11-10 16:48:20 UTC,José López,José López,0,...,La Voila,10:47,0,1,https://web.fulcrumapp.com/photos/view?photos=...,NaN,https://web.fulcrumapp.com/api/v2/file?context...,2,no,11:02
23,9b280ed5-61df-497d-8f64-7b847a08e0ea,be7db0e0-83ad-4486-aa8f-7d31402c2b92,be7db0e0-83ad-4486-aa8f-7d31402c2b92,Abastessen,1,2022-11-10 16:37:01 UTC,2022-11-10 16:38:01 UTC,Mariana Sáenz Gómez Ortigoza,Mariana Sáenz Gómez Ortigoza,0,...,Abastessen,10:50,0,2,https://web.fulcrumapp.com/photos/view?photos=...,NaN,https://web.fulcrumapp.com/api/v2/file?context...,5,yes,11:10
24,17b5c8ed-6501-43bc-b16f-5008cdeb95d7,27bd6132-61df-496d-b780-9db89359dfc8,27bd6132-61df-496d-b780-9db89359dfc8,La central,1,2022-11-10 16:36:26 UTC,2022-11-10 16:37:10 UTC,José López,José López,0,...,La central,10:35,2,1,https://web.fulcrumapp.com/photos/view?photos=...,NaN,https://web.fulcrumapp.com/api/v2/file?context...,2,no,11:00
25,1143e8d5-91ca-4d13-9a25-6f1b728bb91b,e648abf8-df90-46a2-af06-ee5d9662078d,e648abf8-df90-46a2-af06-ee5d9662078d,Súper Boom,1,2022-11-10 16:23:43 UTC,2022-11-10 16:25:17 UTC,Mariana Sáenz Gómez Ortigoza,Mariana Sáenz Gómez Ortigoza,0,...,Súper Boom,10:32,1,2,https://web.fulcrumapp.com/photos/view?photos=...,NaN,https://web.fulcrumapp.com/api/v2/file?context...,3,no,10:46
26,b0f64dbe-1ef5-415a-a91a-c470c255b68d,cfb746bd-5e38-4361-9f45-be1af04f11da,cfb746bd-5e38-4361-9f45-be1af04f11da,Tripoli,1,2022-11-10 16:18:50 UTC,2022-11-10 16:19:47 UTC,Mariana Sáenz Gómez Ortigoza,Mariana Sáenz Gómez Ortigoza,0,...,Tripoli,09:32,0,2,https://web.fulcrumapp.com/photos/view?photos=...,NaN,https://web.fulcrumapp.com/api/v2/file?context...,4,no,10:11
27,f1c82664-47a4-480f-a242-bfa2d81c0d07,a626a0df-ca03-4bc9-b0c7-9d1df43daafa,a626a0df-ca03-4bc9-b0c7-9d1df43daafa,Nussett,1,2022-11-10 16:14:35 UTC,2022-11-10 16:16:12 UTC,José López,José López,0,...,Nussett,10:14,0,1,https://web.fulcrumapp.com/photos/view?photos=...,NaN,https://web.fulcrumapp.com/api/v2/file?context...,4,no,10:30
28,613cb0b4-7aa9-478b-a8bd-f80b31ff18e4,119a1eaf-2d72-4792-94dd-23451e9daaec,119a1eaf-2d72-4792-94dd-23451e9daaec,Tamales Don Ignacio,1,2022-11-10 15:39:35 UTC,2022-11-10 15:41:17 UTC,José López,José López,0,...,Tamales Don Ignacio,09:40,1,0,https://web.fulcrumapp.com/photos/view?photos=...,NaN,https://web.fulcrumapp.com/api/v2/file?context...,2,no,09:57
29,e00ade25-e31b-410f-aed1-0aea780ea3ff,dda5dde0-71ac-4d49-a19d-f9194bf76666,dda5dde0-71ac-4d49-a19d-f9194bf76666,Aqua clyva,1,2022-11-09 22:02:13 UTC,2022-11-09 22:08:11 UTC,Juan Spínola,Juan Spínola,0,...,Aqua clyva,16:02,0,1,NaN,NaN,NaN,2,no,16:08
30,7a620a44-774b-49ca-b340-b905328703d3,28a2af8e-8b1d-4acf-a077-0945049e826c,28a2af8e-8b1d-4acf-a077-0945049e826c,San Juditas,1,2022-11-09 22:14:50 UTC,2022-11-09 22:21:12 UTC,Luis Lara,Luis Lara,0,...,San Juditas,16:15,3,1,https://web.fulcrumapp.com/photos/view?photos=...,NaN,https://web.fulcrumapp.com/api/v2/file?context...,4,no,16:21
31,871dc2b3-f27e-47c9-9e8e-cdc64650cd6c,1c566bed-bbc4-47a7-88d2-8d00dc535bcf,1c566bed-bbc4-47a7-88d2-8d00dc535bcf,Tecate,1,2022-11-09 20:51:52 UTC,2022-11-09 20:58:07 UTC,Luis Lara,Luis Lara,0,...,Tecate,14:52,1,2,https://web.fulcrumapp.com/photos/view?photos=...,NaN,https://web.fulcrumapp.com/api/v2/file?context...,5,no,14:58
32,35f6404a-50cf-4064-84fa-0040c3abc3ad,8f7775ce-161e-47ae-8f03-063ecac52fc8,8f7775ce-161e-47ae-8f03-063ecac52fc8,Tecate,1,2022-11-09 20:50:07 UTC,2022-11-09 20:56:59 UTC,Juan Spínola,Juan Spínola,0,...,Tecate,14:52,1,2,NaN,NaN,NaN,1,no,14:56
33,06f95065-77e8-4de8-9462-edfb34800898,227091c9-d136-428b-b0dd-f205f0675832,227091c9-d136-428b-b0dd-f205f0675832,San Juditas,1,2022-11-09 20:30:37 UTC,2022-11-09 20:33:26 UTC,Juan Spínola,Juan Spínola,0,...,San Juditas,14:30,4,1,https://web.fulcrumapp.com/photos/view?photos=...,NaN,https://web.fulcrumapp.com/api/v2/file?context...,2,no,14:32
34,dd49ed79-b980-462e-98e7-d7abd6c1cbb4,ae8ea7eb-e3f3-4d44-926e-6205f04cf6e5,ae8ea7eb-e3f3-4d44-926e-6205f04cf6e5,Six,1,2022-11-09 18:01:35 UTC,2022-11-09 18:02:38 UTC,Diego Galicia Lugo,Diego Galicia Lugo,0,...,Six,11:47,0,1,NaN,NaN,NaN,1,no,11:50

In [ ]:
#Eliminar columnas innecesarias
datam1=datam.drop(["picture_cargo_being_delivered_captions","picture_cargo_being_delivered","picture_cargo_being_delivered_urls"],axis=1)
datam1

In [5]:
datam1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 24 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   _child_record_id                 35 non-null     object
 1   _record_id                       35 non-null     object
 2   _parent_id                       35 non-null     object
 3   _title                           35 non-null     object
 4   _version                         35 non-null     int64
 5   _created_at                      35 non-null     object
 6   _updated_at                      35 non-null     object
 7   _created_by                      35 non-null     object
 8   _updated_by                      35 non-null     object
 9   _index                           35 non-null     int64
 10  _geometry                        35 non-null     object
 11  _latitude                        35 non-null     float64
 12  _longitude                       35 non-null     float64
 13  _changeset_id                    35 non-null     object
 14  _created_duration                35 non-null     int64
 15  _updated_duration                35 non-null     int64
 16  _edited_duration                 35 non-null     int64
 17  name_of_the_store                35 non-null     object
 18  entering_the_store               35 non-null     object
 19  number_of_customers_in_store     35 non-null     int64
 20  number_of_suppliers_in_store     35 non-null     int64
 21  number_of_cases_boxes_delivered  35 non-null     int64
 22  trolley_in_use                   35 non-null     object
 23  leaving_the_store                35 non-null     object
dtypes: float64(2), int64(8), object(14)
memory usage: 6.7+ KB

In [6]:
#Filtro para separar variables cualitativas
fdatam_cual=datam1.iloc[:,[0,1,2,3,5,6,7,8,10,13,17,18,22,23]]

In [8]:
#Sustituir valores nulos por valores no nulos hacia adelante forward fill" ("ffill")
fdatam_cual=fdatam_cual.fillna(method="bfill")

In [9]:
#Identificar valores nulos por columna
valores_nulos=fdatam_cual.isnull().sum()
valores_nulos

_child_record_id      0
_record_id            0
_parent_id            0
_title                0
_created_at           0
_updated_at           0
_created_by           0
_updated_by           0
_geometry             0
_changeset_id         0
name_of_the_store     0
entering_the_store    0
trolley_in_use        0
leaving_the_store     0
dtype: int64

In [7]:
#Filtro para separar variables cuantitativas
fdatam_cuan=datam1.iloc[:,[4,9,11,12,14,15,16,19,20,21]]

In [10]:
#Método aplicando Cuartiles. Encuentro cuartiles 0.25 y 0.75
y=fdatam_cuan

percentile25=y.quantile(0.25) #Q1
percentile75=y.quantile(0.75) #Q3
iqr= percentile75 - percentile25

Limite_Superior_iqr= percentile75 + 1.5*iqr
Limite_Inferior_iqr= percentile25 - 1.5*iqr
print("Limite superior permitido", Limite_Superior_iqr)
print("Limite inferior permitido", Limite_Inferior_iqr)

Limite superior permitido _version                             1.000000
_index                               0.000000
_latitude                           19.118961
_longitude                         -98.181767
_created_duration                    0.000000
_updated_duration                  177.250000
_edited_duration                   172.000000
number_of_customers_in_store         5.000000
number_of_suppliers_in_store         3.500000
number_of_cases_boxes_delivered     12.000000
dtype: float64
Limite inferior permitido _version                            1.000000
_index                              0.000000
_latitude                          18.935810
_longitude                        -98.319111
_created_duration                   0.000000
_updated_duration                 -40.750000
_edited_duration                  -32.000000
number_of_customers_in_store       -3.000000
number_of_suppliers_in_store       -0.500000
number_of_cases_boxes_delivered    -4.000000
dtype: float64

In [11]:
data3=fdatam_cuan[(y<=Limite_Superior_iqr)&(y>=Limite_Inferior_iqr)]
data3

,_version,_index,_latitude,_longitude,_created_duration,_updated_duration,_edited_duration,number_of_customers_in_store,number_of_suppliers_in_store,number_of_cases_boxes_delivered
0,1,0,19.059667,-98.233864,NaN,3.0,64.0,1.0,1.0,NaN
1,1,0,19.053049,-98.229422,NaN,80.0,80.0,0.0,2.0,NaN
2,1,0,19.051740,-98.232677,NaN,61.0,86.0,0.0,1.0,12.0
3,1,0,19.052990,-98.233991,NaN,7.0,48.0,0.0,1.0,3.0
4,1,0,19.055389,-98.230130,NaN,76.0,76.0,0.0,1.0,1.0
5,1,0,19.053104,-98.227161,NaN,53.0,53.0,NaN,1.0,3.0
6,1,0,19.045903,-98.203487,0.0,8.0,8.0,1.0,1.0,3.0
7,1,0,19.023488,-98.203281,0.0,4.0,4.0,2.0,1.0,3.0
8,1,0,19.046459,-98.193698,0.0,116.0,116.0,2.0,1.0,2.0
9,1,0,19.065868,-98.310562,NaN,NaN,NaN,3.0,2.0,11.0
10,1,0,19.064508,-98.311303,NaN,167.0,167.0,2.0,2.0,12.0
11,1,0,19.047385,-98.204255,0.0,130.0,130.0,NaN,1.0,5.0
12,1,0,19.048819,-98.200050,0.0,11.0,11.0,0.0,1.0,NaN
13,1,0,18.999429,-98.274060,0.0,78.0,78.0,1.0,3.0,8.0
14,1,0,18.999426,-98.274079,0.0,46.0,46.0,2.0,1.0,2.0
15,1,0,19.006088,-98.265674,0.0,50.0,50.0,2.0,NaN,10.0
16,1,0,19.006137,-98.265682,0.0,56.0,56.0,0.0,2.0,6.0
17,1,0,19.006115,-98.265670,0.0,41.0,41.0,0.0,1.0,2.0
18,1,0,19.004101,-98.266502,0.0,41.0,41.0,3.0,1.0,4.0
19,1,0,19.004110,-98.266491,0.0,81.0,81.0,2.0,1.0,2.0
20,1,0,19.004503,-98.266188,0.0,76.0,76.0,4.0,3.0,6.0
21,1,0,19.004481,-98.266204,0.0,40.0,40.0,4.0,2.0,5.0
22,1,0,18.999598,-98.274838,0.0,68.0,68.0,0.0,1.0,2.0
23,1,0,19.001842,-98.271896,0.0,60.0,60.0,0.0,2.0,5.0
24,1,0,19.001730,-98.272087,0.0,43.0,43.0,2.0,1.0,2.0
25,1,0,19.005120,-98.266486,0.0,94.0,94.0,1.0,2.0,3.0
26,1,0,19.005652,-98.267596,0.0,57.0,57.0,0.0,2.0,4.0
27,1,0,19.005692,-98.267617,0.0,97.0,97.0,0.0,1.0,4.0
28,1,0,19.004079,-98.266771,0.0,2.0,2.0,1.0,0.0,2.0
29,1,0,19.026688,-98.249335,0.0,NaN,NaN,0.0,1.0,2.0
30,1,0,19.025176,-98.249031,0.0,NaN,NaN,3.0,1.0,4.0
31,1,0,19.030839,-98.249791,0.0,1.0,1.0,1.0,2.0,5.0
32,1,0,19.030743,-98.249907,0.0,NaN,NaN,1.0,2.0,1.0
33,1,0,19.025156,-98.249055,0.0,168.0,168.0,4.0,1.0,2.0
34,1,0,NaN,NaN,0.0,62.0,62.0,0.0,1.0,1.0

In [12]:
#Segundo método de sustitución de valores nulos
#Sustituir valores nulos con la media
data3=data3.fillna(round(fdatam_cuan.median(),1))

In [13]:
#Identificar valores nulos por columna
valores_nulos=data3.isnull().sum()
valores_nulos

_version                           0
_index                             0
_latitude                          0
_longitude                         0
_created_duration                  0
_updated_duration                  0
_edited_duration                   0
number_of_customers_in_store       0
number_of_suppliers_in_store       0
number_of_cases_boxes_delivered    0
dtype: int64